server {
    listen 80;
    root /usr/share/nginx/html;

    set $backend_server http://backend:3000;
    resolver 127.0.0.11 valid=5s;

    location /api/ {
       proxy_pass $backend_server;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
     }

    # Always return index.html without caching to cover new version of SPA loading
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        try_files $uri /index.html =404;
    }

    # Caching static files for 1 year (JS, CSS, зображення) - immutable assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    # Return index.html if there is an error
    location / {
        try_files $uri $uri/ /index.html;
    }
}
